name: Create Tree
# Build the tree of folders and files for the website.

on: 
  push:
    branches: [ "src" ]
  
  # Run this workflow manually from the Actions tab  
  workflow_dispatch:
  
      
jobs:
  build:
    permissions: write-all

    runs-on: ubuntu-latest
    
    steps:         
      - name: Actions Checkout v4
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Python Code
        shell: python
        run: |
            import os
            import sys
            import subprocess

            folder_list = ["files", "files/assets", "files/assets/css", "images", "pages", 
                 "pages/general", "pages/statement", "pages/statement1",] 
                 #".github", "#.github/workflows",] <-- manually created

            file_list = ["pages/index.en.md", "pages/index.fr.md", 
                "pages/general/document-primer.en.md", "pages/general/document-primer.fr.md", 
                "pages/statement/2006-07-31-pv5500-res1696-2006-ip.en.md", "pages/statement/2006-07-31-pv5500-res1696-2006-ip.fr.md", 
                "pages/statement/2006-12-23-pv5612-res1737-2006-ip.en.md", "pages/statement/2006-12-23-pv5612-res1737-2006-ip.fr.md", 
                "pages/statement/2007-03-24-pv5647-res1747-2007-ip.en.md", "pages/statement/2007-03-24-pv5647-res1747-2007-ip.fr.md", 
                "pages/statement/2008-03-03-pv5848-res1803-2008-ip.en.md", "pages/statement/2008-03-03-pv5848-res1803-2008-ip.fr.md", 
                "pages/statement/2010-06-09-pv6335-res1929-2010-ip.en.md", "pages/statement/2010-06-09-pv6335-res1929-2010-ip.fr.md", 
                "pages/statement/2015-07-20-pv7488-res2231-2015-ip.en.md", "pages/statement/2015-07-20-pv7488-res2231-2015-ip.fr.md", 
                "pages/statement/introduction.en.md", "pages/statement/introduction.fr.md", 
                "pages/statement1/2018-12-12-pv8418-ip.en.md", "pages/statement1/2018-12-12-pv8418-ip.fr.md", 
                "pages/statement1/2019-06-26-pv8564-ip.en.md", "pages/statement1/2019-06-26-pv8564-ip.fr.md", 
                "pages/statement1/2019-12-19-pv8695-ip.en.md", "pages/statement1/2019-12-19-pv8695-ip.fr.md", 
                "pages/statement1/2020-08-17-res-draft-2020-805-ip.en.md", "pages/statement1/2020-08-17-res-draft-2020-805-ip.fr.md", 
                "pages/statement1/2021-06-30-pv8811-ip.en.md", "pages/statement1/2021-06-30-pv8811-ip.fr.md", 
                "pages/statement1/2021-12-14-pv8930-ip.en.md", "pages/statement1/2021-12-14-pv8930-ip.fr.md", 
                "pages/statement1/2022-06-30-pv9085-ip.en.md", "pages/statement1/2022-06-30-pv9085-ip.fr.md", 
                "pages/statement1/2022-12-19-pv9225-ip.en.md", "pages/statement1/2022-12-19-pv9225-ip.fr.md", 
                "pages/statement1/2023-07-06-pv9367-ip.en.md", "pages/statement1/2023-07-06-pv9367-ip.fr.md", 
                "pages/statement1/2023-12-18-pv9511-ip.en.md", "pages/statement1/2023-12-18-pv9511-ip.fr.md", 
                "pages/statement1/2024-06-24-pv9666-ip.en.md", "pages/statement1/2024-06-24-pv9666-ip.fr.md", 
                "pages/statement1/2024-12-17-pv9818-ip.en.md", "pages/statement1/2024-12-17-pv9818-ip.fr.md", 
                "pages/statement1/2025-03-12-pv9877-closed-ip.en.md", "pages/statement1/2025-03-12-pv9877-closed-ip.fr.md", 
                "pages/statement1/introduction1.en.md", "pages/statement1/introduction1.fr.md", 
                "files/assets/css/custom.css", "files/index.html", 
                "images/favicon-flag.svg", "images/website-logo.svg", "conf.py", ".gitignore",] 

            for folder in folder_list:
              os.makedirs(folder, exist_ok=True)

            for path_file in file_list:
              if not os.path.exists(path_file):
                  os.mknod(path_file)

            #print('Current Working Directory:', os.getcwd())

            subprocess.run('''
                # Git instructions - performed by bash
                git config user.name "iran-information"
                git config user.email "iran.information@protonmail.com"          
                git add .
                git commit -m "generated"
                git push''',
                shell=True, check=True, executable='/bin/bash')
                
